name: Test School Java

on:
  pull_request:
    branches: ["main", "master"]

jobs:
  test-project:
    uses: cx-actions-2025/fm-actions/.github/workflows/school-java.yaml@bc1e770dd53c9b10498863fa563d6ef5a53da221
    with:
        team-name: ${{ vars.TEAM_NAME }}
    secrets:
        test-repo: ${{ secrets.TEST_REPO }}
        auth-token: ${{ secrets.AUTH_TOKEN }}
        backend-url: ${{ secrets.BACKEND_URL }}
        auth-key: ${{ secrets.AUTH_KEY }}
